services:
  # 应用服务
  app:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./backend:/app
    
  # MongoDB service
  mongo_user:
    image: mongo
    restart: always
    container_name: mongo_user
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: yehsimon
      MONGO_INITDB_ROOT_PASSWORD: superstrongpsw
    volumes:
      - ./user_register/:/data/db/
  mongo_songlyrics:
    image: mongo
    restart: always
    container_name: mongo_songlyrics
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: yehsimon
      MONGO_INITDB_ROOT_PASSWORD: superstrongpsw
    volumes:
      - ./song_lyrics/:/data/db/
    
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant_vector
    ports:
      - 6445:6334
      - 6444:6333
    volumes:
      - ./backend/app/data:/qdrant_data
