services:
  app:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./backend:/app
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: yehsimon
      MONGO_INITDB_ROOT_PASSWORD: superstrongpsw
    volumes:
      - ./db_data/:/data/db/
